<?php /** */?>

<?php if($this->isActive()): ?>
    <!--Addonline Google Universal Analytics Tracker Section start -->
    <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '<?php echo $this->getAccountId(); ?>', '<?php echo $this->getRequest()->getHttpHost() ?>');
        ga('set', 'anonymizeIp', <?php echo $this->isAnonymizeIp()?>);
        <?php if($this->isSSL()):?>
        ga('set', 'forceSSL', true);
        <?php endif; ?>        
        ga('send', 'pageview');              
    </script>
    <?php echo $this->getChildHtml(); ?>
    <!--Addonline Google Universal Analytics Tracker Section end -->
<?php endif; ?>