<div class="cart">
<?php 
    $cart = Mage::getModel('checkout/cart')->getQuote();
    foreach ($cart->getAllItems() as $item) {
        $this->getChild("mini-fiche")->setData("product", $item->getProduct());
        $this->getChild("mini-fiche")->setData("height", 210);
        $this->getChild("mini-fiche")->setData("width", 244);
        echo $this->getChildHtml("mini-fiche", false);
        echo $productName = $item->getProduct()->getName();
        echo $productPrice = $item->getProduct()->getPrice();
    }
?>
</div>
