<div class="cart-min">
<?php 
	echo $this->getChildHtml('j2tajaxcheckout');
    // $cart = Mage::getModel('checkout/cart')->getQuote();
    // foreach ($cart->getAllItems() as $item) {
    // 	?><div class="mini"><?php
    //     $this->getChild("mini-fiche")->setData("product", $item->getProduct());
    //     $this->getChild("mini-fiche")->setData("height", 140);
    //     $this->getChild("mini-fiche")->setData("width", 140);
    //     echo $this->getChildHtml("mini-fiche", false);
    //     ?></div><?php
    // }
?>
</div>
