<?php if ($this->getListRelais()) :
$i=0;
foreach ($this->getListRelais() as $relais) : ?>
<?php $type="poste"; 
    if($relais->typeDePoint=="A2P") {
    	$type="commercant";
    }elseif($relais->typeDePoint=="CIT") {
    	$type="cityssimo";
    }
?>
<div class="point_retrait" id="point_retrait_<?php echo $i; ?>">
	<div class="distance">A <?php echo number_format (intval($relais->distanceEnMetre)/1000, 2, ',', '') ?>km</div>
	<div class="point <?php echo $type ?>"><?php if (in_array($relais->typeDePoint, array("BPR","CDI", "ACP"))): ?>Bureau de poste<?php elseif($relais->typeDePoint=="A2P"):?>Commerçant<?php elseif($relais->typeDePoint=="CIT"):?>Consigne cityssimo<?php endif;?></div>
	<?php if ($relais->accesPersonneMobiliteReduite) : ?>
		<img class="handicap" alt="accessibles aux personnes en situation de handicap" src="<?php echo $this->getSkinUrl("images/socolissimo/picto_handicap.png"); ?>" />
	<?php endif; ?>
	<div class="adresse_point">
		<b><?php echo $relais->nom ?></b><br />
		<?php echo $relais->adresse1 ?><br />
		<?php echo $relais->codePostal.' '.$relais->localite ?>
	</div>
	<?php if (!$relais->congesTotal) :?>
	<button type="button" class="btn_socolissimoChoisir button <?php echo $type ?>" onclick="choisirRelais('<?php echo $i; ?>')" ><span>Choisir <?php if (in_array($relais->typeDePoint, array("BPR","CDI", "ACP"))): ?>ce bureau de poste<?php elseif($relais->typeDePoint=="A2P"):?>ce commerçant<?php elseif($relais->typeDePoint=="CIT"):?> cette consigne cityssimo<?php endif;?></span></button>
	<?php else :?>
	<button type="button" class="btn_socolissimoChoisir button" ><span>en congés</span></button> 	
	<?php endif;?>
</div>
<?php 
$i++;
endforeach;
endif;?>
