type: mysql
name: addonline_aomagento_magento
backup_path: addonline_aomagento_magento_*.sql
update: |
  UPDATE core_config_data SET value='http://aomagento.username.jetpulp.dev/' WHERE value='http://aomagento.addonline.biz/';
  UPDATE cms_page SET content=REPLACE(content,'http://aomagento.username.jetpulp.dev/','http://aomagento.addonline.biz/');
  UPDATE cms_block SET content=REPLACE(content,'http://aomagento.username.addonline.biz/','http://aomagento.addonline.biz/');
  UPDATE catalog_product_entity_text SET value=REPLACE(value,'http://aomagento.username.addonline.biz/','http://aomagento.addonline.biz/') WHERE attribute_id IN (97,506);
  UPDATE core_config_data SET value='mail.add-online.fr' WHERE path='system/smtp/host';
  UPDATE core_config_data SET value='1' WHERE path='dev/log/active';
  UPDATE core_config_data SET value='1' WHERE path='dev/template/allow_symlink';