<?php

?>

<div class="page-title">
    <h2><?php echo $this->__('Checkout') ?></h2>
</div>
<ul class="paiement" id="etapesCommande">
<li><a href="<?php echo $this->helper('checkout/cart')->getCartUrl() ?>" ></a><span>Votre panier</span></a></li>
<li><span>Informations de facturation</span></li>
<li><span>Informations de livraison</span></li>
<li><span>Paiement de la commande</span></li>
</ul>
<ol class="opc" id="checkoutSteps">
<script type="text/javascript">
Validation.creditCartTypes.JCB = [new RegExp('^(35[0-9]{14}|(2131|1800)[0-9]{11})$'), new RegExp('^([0-9]{3})?$'), true];
Validation.creditCartTypes.DICL = [new RegExp('^((300|305)[0-9]{11}|36[0-9]{12}|55[0-9]{14})$'), new RegExp('^([0-9]{3})?$'), false];
</script>
<?php $_code=$this->getMethodCode() ?>
<li class="section allow active" id="opc-billing">
	<div class="step-title">
		<span class="number">1</span>
		<h3>Votre paiement</h3>
	</div>
	<div style="" class="step a-item" id="checkout-step-billing">
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/ogonedirectlink.js') ?>"></script>
		<script type="text/javascript">
		//<![CDATA[
		    var payment = new PaymentOgone('co-payment-form', '<?php echo $this->getUrl('ogonedirectlink/ogone/valid') ?>','<?php echo $this->getUrl('checkout/onepage/success') ?>');
		//]]>
		</script>
                <form action="" id="co-payment-form" method="post" onsubmit="return false;">
			<input type="hidden" name="payment[method]" value="<?php echo $_code ?>"  />
			<h4>Paiement par carte bancaire</h4>
			
			<a href="<?php echo $this->getUrl('checkout/onepage/index/') ?>step/payment" class="changerModePaiement">Changer de mode de paiement</a>

			<div class="input-box type">
				<label >Montant total à payer : </label>
				<div class="total_a_payer"><?php echo $this->getMontantTotal() ?></div>
			</div>
						
			<div class="input-box type">
				<label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span> :</label>
				<select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                   <option value="">--<?php echo $this->__('Please Select') ?>--</option>
	                <?php  $_ccType = $this->getInfoData('cc_type') ?>
    	            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>" <?php if($_typeCode==$_ccType): ?>selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
        	        <?php endforeach ?>
				</select>
			</div>

			<div class="input-box">
				<label for="<?php echo $_code ?>_cc_owner"><?php echo $this->__('Name on Card') ?> :</label>
				<input type="text" title="<?php echo $this->__('Name on Card') ?>" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner'))  ?>" maxlength="30" class="input-text length_330"  />
			</div>
			
			<div class="input-box fullSize">
                <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?> <span class="required">*</span> :</label>
                <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type length_330"  value=""  maxlength="30" onblur="return verifmaxlengthnumc()"/>
			</div>
			
			<div class="input-box date">
                <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span> :</label>
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]"  class="required-entry" >
                <?php  $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="required-entry"  >
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach  ?>
                </select>
			</div>
			
			<div class="input-box" id="code">
                <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span> :</label>
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="required-entry input-text validate-cc-cvn length_12" maxlength="30" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" onblur="return verifmaxlengthnumc4()"/>
				<span>Le code de sécurité correspond aux 3 derniers chiffres au dos de votre carte bancaire</span>
			</div>
			
			<div class="cobraSecurisation">Notre site internet Cobrason.com utilise la solution e-Commerce Ogone, reconnue par de nombreux acteurs du monde financier. Elle a été développée pour que vous puissiez effectuer vos paiements dans un environnement ergonomique et convivial, avec une sécurité optimale. Tout cela, dans le plus pur respect de votre vie privée. Le logo ci-dessous et la mention "Paiement sécurisé par Ogone" vous garantissent donc un achat en toute sérénité !</div>
			<p class="required"><?php echo $this->__('* Required Fields') ?></p>
			<div class="buttons-set">
				<button type="submit"><span>Valider</span></button>
			</div>
			
			<p class="cobraphone">
				<span class="ligne1">Au <span>0 825 30 10 80</span>* nos conseillers vous aident &agrave; passer commande.</span><br/>
				<span class="ligne2">Du Lundi au Samedi de 10h00 &agrave; 19h00 sans interruption. * 0,15&euro; ttc/min depuis un poste fixe.</span>
			</p>
		</form>
		<script type="text/javascript">payment.init();</script>
	</div>
</li>
</ol>

<script type="text/javascript">
    function verifmaxlengthnumc(){
        if(jQuery('#ogonedirectlink_cc_type').val() == 'AE'){
            var taille = jQuery('#ogonedirectlink_cc_number').val().length;
            if(taille != 15) {
                //if (event.keyCode != 8 && event.keyCode != 13){ //different de backspace et Enter bouton
                alert('Ce champ doit contenir 15 caract'+String.fromCharCode(232)+'res');
                return false;
                // }else
            //return true;
            }else
                return true;
        }else
            return true;

    }
    function verifmaxlengthnumc4(){
        if(jQuery('#ogonedirectlink_cc_type').val() == 'AE'){//if type American Express
            var taille = jQuery('#ogonedirectlink_cc_cid').val().length;
            if(taille != 4) {
                //if (event.keyCode != 8 && event.keyCode != 13){//different de backspace et Enter bouton
                alert('Ce champ doit contenir 4 caract'+String.fromCharCode(232)+'res');
                return false;
                //}else
            //return true;
            }else
                return true;
        }else
            return true;

    }
</script>


