#!/bin/sh

##################################################################
#
#  Pre-push Git Hook
#
#  Prevent pushing too big repo, or repo without some required files
#
##################################################################

reposize=$(git count-objects -v | grep size-pack | cut -d' ' -f2)

if [ $reposize -gt 102400 ];
then
    echo "This repos is to big ($(git count-objects -vH | grep size:)), check if ou haven't commited too many useless big files, user images, log files, etc..."
	exit 1
fi

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`

for requiredfile in 'README.md' 'phpcs.xml' '.gitlab-ci.yml' 'composer.json' 'composer.lock' '.gitignore'
do
    if ! test -e "$PROJECT/$requiredfile";
    then
        echo "This repos doesn't contain a $requiredfile file, please create one before push again"
        exit 1
    fi
done
