<?php echo $this->getChildHtml("responsiveslider"); ?>

<?php echo $this->getChildHtml("home-circles"); ?>

<?php echo $this->getChildHtml("home-page-descript"); ?>

<?php echo $this->getChildHtml("home-page-mea"); ?>

<div class="home-mea">
	<div class="first">
		<?php echo $this->getChildHtml("home-mea1"); ?>
	</div>
	<div class="last">
		<?php echo $this->getChildHtml("home-cat-1"); ?>
	</div>
</div>

