<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_code = $this->getMethodCode(); ?>

<fieldset id="payment_form_<?php echo $_code ?>" class="form-list" >
<img src="<?php echo $this->getSkinUrl('images/media/logo_sprint_secure_35x_fre.jpg') ?>" alt="3 fois sans frais" />
<ul id="payment_desc_<?php echo $_code ?>">
	<li><br/>
		3X sans frais<br/>
		Crédit en 5, 10, 20 fois<br/><br/>

		Sprint secure est un service gratuit pour vous nécessitant l'ouverture d'un compte et d'une réserve auprès de notre partenaire Franfinance. 
		Un crédit vous engage et doit être remboursé.
	</li>
</ul>
</fieldset>