<?php

?>
<div id="layer_gls" class="layer">
	<div id="layer_gls_wrapper" >
		<div>
			<h3>Selectionnez votre point Relais Mondial Relay</h3><a class="close"></a>
			<div class="contenu">
				<div id="gls_headers">
				<span>Votre code postal</span>
				<input type="text" id="cp_recherche" />
				<button id="cp_recherche_bouton">Rechercher</button>
				<input type="checkbox" id="sms_checkbox" />
				<span>Etre averti de ma livraison par SMS</span>
				<input type="text" id="num_telephone" />
				</div>
				<div id="col_gauche_gls">
					<div id="map_gls"></div>
				</div>
				<div id="col_droite_gls"></div>
			</div>
		</div>
	</div>
</div>