<?php if ($this->getListRelay()) :
$i=0;
foreach ($this->getListRelay() as $relais) : ?>
<div class="gls_point_relay" id="gls_point_relay_<?php echo $i; ?>">
	<span><?php echo $relais['relayName']; ?></span>
	<span><?php echo $relais['relayAddress']; ?></span>
	<span><?php echo $relais['relayZipCode']; ?></span>
	<span><?php echo $relais['relayCity']; ?></span>
</div>
<?php
$i++;
endforeach;
endif;?>
