<?php if ($this->getListRelay()) :
$i=0;
foreach ($this->getListRelay() as $relais) : ?>
<div class="gls_point_relay" id="gls_point_relay_<?php echo $i; ?>">
	<span class="GLS_relay_index"><?php echo $i; ?></span>
	<span class="GLS_relay_id"><?php echo $relais['relayId']; ?></span>
	<span class="GLS_relay_name"><?php echo $relais['relayName']; ?></span>
	<span class="GLS_relay_address"><?php echo $relais['relayAddress']; ?></span>
	<span class="GLS_relay_zipcode"><?php echo $relais['relayZipCode']; ?></span>
	<span class="GLS_relay_city"><?php echo $relais['relayCity']; ?></span>
	<span class="GLS_relay_latitude"><?php echo $relais['relayLatitude']; ?></span>
	<span class="GLS_relay_longitude"><?php echo $relais['relayLongitude']; ?></span>
	<div>
		<span class="GLS_relay_horaires">Voir les horaires</span>
		<button>Choisir ce lieu</button>
	</div>
	<span class="GLS_relay_hours">
		<table cellpadding="0" cellspacing="0">
		<?php
		$aDays = array('0' => 'Lundi','1' => 'Mardi','2' => 'Mercredi','3' => 'Jeudi','4' => 'Vendredi','5' => 'samedi','6' => 'Dimanche');
		foreach($relais['relayWorkingDays'] as $day => $openHours){
			echo '<tr>';
			echo '<td>'.$aDays[$day].'</td>';
			$hours = '';
			if($openHours['breaks']['from']){
				$hours = '<td class="day">'.substr_replace(substr($openHours['hours']['from'],0,4), 'h'.$openHours['hours']['from'][2], 2,1).' - '.substr_replace(substr($openHours['breaks']['from'],0,4), 'h'.$openHours['breaks']['from'][2], 2,1).' / '.substr_replace(substr($openHours['breaks']['to'],0,4), 'h'.$openHours['breaks']['to'][2], 2,1).' - '.substr_replace(substr($openHours['hours']['to'],0,4), 'h'.$openHours['hours']['to'][2], 2,1).'</td>';
			}else{
				$hours = '<td>'.substr_replace(substr($openHours['hours']['from'],0,4), 'h'.$openHours['hours']['from'][2], 2,1).' - '.substr_replace(substr($openHours['hours']['to'],0,4), 'h'.$openHours['hours']['to'][2], 2,1).'</td>';
			}
			echo $hours;
			echo '</tr>';
		}
		?>
			<tr>
				<td>Dimanche</td>
				<td>fermé</td>
			</tr>
		</table>
	</span>
</div>
<?php
$i++;
endforeach;
endif;?>
