<div class="footer-inner">
<!-- <div class="footer-select">
    <p class="language-select"><?php echo $this->__('Interface Locale: %s', $this->getLanguageSelect()) ?></p>
    <p class="theme-select">
        <?php echo $this->helper('bubble_admintheme')->__('Current Theme:'); ?>
        <?php echo $this->getLayout()->createBlock('bubble_admintheme/adminhtml_themes_select')->getHtml(); ?>
    </p>
</div> -->
<div class="legality">
    <!-- <address class="copyright"><?php echo $this->__('Magento&trade; is a trademark of Magento Inc.') ?></address> -->
    <!-- <p><?php echo $this->__('Copyright &copy; %s Magento Inc.', date('Y')) ?></p> -->
    <p><?php echo $this->__('Magento ver. %s', Mage::getVersion()) ?></p>
    <p><a href="https://www.jetpulp.fr" target="_blank">JETPULP</a> - Copyright &copy; <?php echo date('Y'); ?></p>
    <!-- <p><a href="http://www.magentocommerce.com" id="footer_connect"><?php echo $this->__('Connect with the Magento Community') ?></a></p>
    <input id="footer_bug_tracking" type="hidden" value="" /> -->
</div>
<script type="text/javascript">
    // $('footer_bug_tracking').target = 'Varien_External';
    // $('footer_connect').target = 'Varien_External';
    // function setInterfaceLanguage(evt){
    //     var elem = Event.element(evt);
    //     if(elem){
    //         setLocation('<?php echo $this->getChangeLocaleUrl() ?>locale/'+elem.value+'/<?php echo $this->getRefererParamName() ?>/<?php echo $this->getUrlForReferer() ?>');
    //     }
    // }
    // Event.observe('interface_locale', 'change', setInterfaceLanguage);

    // // Bubble_AdminTheme
    // function setInterfaceTheme(evt){
    //     var elem = Event.element(evt);
    //     if(elem){
    //         setLocation('<?php echo $this->getUrl('adminhtml/theme/change'); ?>theme/'+elem.value+'/<?php echo $this->getRefererParamName() ?>/<?php echo $this->getUrlForReferer() ?>');
    //     }
    // }
    // Event.observe('interface_theme', 'change', setInterfaceTheme);
</script>
</div>