<?php
$result = $this->getSlideshowData();
?>
			<div id="slideshow">
	
				<div class="scrollable">
	
	
					<div class="items">
<?php foreach($result as $id => $block): 
$_image = $block['image'];
$_url = $block['url'];
?>
					
					
						
						<?php if( $block['is_product'] ) {
							$_image_produit = $block['product']['image'];
							$_url_produit = $block['product']['url'];
							if($block['image'] == null) {
								$_image = $this->getSkinUrl('images/advancedslideshow/default_bkg.png');
							}
						?>
							<div class="product">
								<img src="<?php echo $_image; ?>" /><?php echo $block['image']; ?>
								<div>
									<a class="product-image" href="<?php echo $_url_produit; ?>"><img src="<?php echo $_image_produit; ?>" /></a>
									<h1 class="product-name"><a href="<?php echo $_url_produit; ?>"><?php echo $block['product']['name']; ?></a></h1>
									<div class="desc std">
                        				<?php echo $this->helper('catalog/output')->productAttribute($block['product'], $block['product']->getShortDescription(), 'short_description') ?>
                        			</div>
                        			<?php echo $this->getPriceHtml($block['product'], true) ?>
								</div>
							</div>
						<?php } else {?>
							<div>
								<a href="<?php echo $_url; ?>"><img src="<?php echo $_image; ?>" /></a>
							</div>
						<?php }?>
						
						
						
						
<?php endforeach ?>
					</div>
	
				</div>
				
				<div class="navi"></div>
				<a href="#" class="next"></a>
				<a href="#" class="prev"></a>
				
			</div>