<?php
$result = $this->getSlideshowData();
?>
	<div id="slideshow">
	
	
		<div id="slideshow_pages">
	
	
			<div class="slideshow_page">
	
	
				<div class="scrollable">
	
	
					<div class="items">
<?php foreach($result as $id => $block): 
$_image = $block['image'];
$_url = $block['url'];
if($block['is_product'])
{
	$_image = $block['product']['image'];
	$_url = $block['product']['url'];
}
?>
					
						<div class="item">
							<a href="<?php echo $_url; ?>"><img src="<?php echo $_image; ?>" border="0" /></a>
						</div>
<?php endforeach ?>
					</div>
	
				</div>
				
				<div class="navi"></div>
				
			</div>
		
	
		</div>
	
	</div>




