<?php if ($this->getListRelais()) :
$i=0;
foreach ($this->getListRelais() as $relais) : ?>
<div class="point_retrait" id="point_retrait_<?php echo $i; ?>">
	<div class="distance">A <?php echo number_format ($relais->getDistance(), 2, ',', '') ?>km</div>
	<div class="point <?php echo $relais->getType() ?>"><?php if ($relais->getType()=="poste"): ?>Bureau de poste<?php elseif($relais->getType()=="commercant"):?>Commerçant<?php elseif($relais->getType()=="cityssimo"):?>Relais cityssimo<?php endif;?></div>
	<div class="adresse_point">
		<b><?php echo $relais->getLibelle() ?></b><br />
		<?php echo $relais->getAdresse() ?><br />
		<?php echo $relais->getCodePostal().' '.$relais->getCommune() ?>
	</div>
	<button type="button" class="btn_socolissimoChoisir button <?php echo $relais->getType();?>" onclick="choisirRelais('<?php echo $i; ?>')" ><span>Choisir ce <?php if ($relais->getType()=="poste"): ?>bureau de poste<?php elseif($relais->getType()=="commercant"):?>commerçant<?php elseif($relais->getType()=="cityssimo"):?>relais cityssimo<?php endif;?></span></button>
</div>
<?php 
$i++;
endforeach;
endif;?>
