<div class="footer-content">
<!-- <div class="bug-report">
    <p><a href="<?php echo $this->getBugreportUrl() ?>" id="footer_bug_tracking"><?php echo $this->__('Help Us Keep Magento Healthy - Report All Bugs') ?></a></p>
    <p><?php echo $this->__('Interface Locale: %s', $this->getLanguageSelect()) ?></p>
    <p><?php echo $this->helper('bubble_admintheme')->__('Current Theme:'); ?>&nbsp;<?php echo $this->getLayout()->createBlock('bubble_admintheme/adminhtml_themes_select')->getHtml(); ?></p>
</div> -->
<!-- <div class="legality">
    <p><a href="http://www.magentocommerce.com" id="footer_connect"><?php echo $this->__('Connect with the Magento Community') ?></a></p>
    <p><?php echo $this->__('Magento&trade; is a trademark of Magento Inc.<br/>Copyright &copy; %s Magento Inc.', date('Y')) ?></p>
</div> -->
<p><?php echo $this->__('Magento ver. %s', Mage::getVersion()) ?></p>
<p><a href="https://www.jetpulp.fr" target="_blank">JETPULP</a> - Copyright &copy; <?php echo date('Y'); ?></p>
<script type="text/javascript">
   /* $('footer_bug_tracking').target = 'Varien_External';
    $('footer_connect').target = 'Varien_External';
    function setInterfaceLanguage(evt){
        var elem = Event.element(evt);
        if(elem){
            setLocation('<?php echo $this->getChangeLocaleUrl() ?>locale/'+elem.value+'/<?php echo $this->getRefererParamName() ?>/<?php echo $this->getUrlForReferer() ?>');
        }
    }
    Event.observe('interface_locale', 'change', setInterfaceLanguage);

    // Bubble_AdminTheme
    function setInterfaceTheme(evt){
        var elem = Event.element(evt);
        if(elem){
            setLocation('<?php echo $this->getUrl('adminhtml/theme/change'); ?>theme/'+elem.value+'/<?php echo $this->getRefererParamName() ?>/<?php echo $this->getUrlForReferer() ?>');
        }
    }
    Event.observe('interface_theme', 'change', setInterfaceTheme);*/
</script>
</div>