<?php
$_product = $this->getData("product");
$_btn_buy = $this->getData("btn_buy") ? $this->getData("btn_buy") : false;
$_width = $this->getData("width") ? $this->getData("width") : 205;
$_height = $this->getData("height") ? $this->getData("height") : 205;
$_helper = $this->getParentBlock()->helper('catalog/output');
$helperao = $this->getParentBlock()->helper('aocatalog');
$_productNameStripped = $this->stripTags($_product->getName(), null, true);
?>
<div class="mini-product">
    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->getParentBlock()->stripTags($this->getParentBlock()->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->getParentBlock()->helper('catalog/image')->init($_product, 'small_image')->keepAspectRatio(TRUE)->resize($_width,$_height); ?>" width="<?php echo $_width; ?>" height="<?php echo $_height; ?>" alt="<?php echo $this->getParentBlock()->stripTags($this->getParentBlock()->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
    <?php echo $this->getParentBlock()->getPriceHtml($_product, true) ?>
    <?php if ($helperao->getReductionPercent($_product) > 0) :?>
        <span class="percentage">-<?php echo $helperao->getReductionPercent($_product); ?>%</span>
    <?php elseif ( $helperao->isNew(null, $_product) ) :?>
        <span class="new"><?php echo __("new"); ?></span>
    <?php endif;?>
    <a href="<?php echo $_product->getProductUrl() ?>" class="product-plus">
        <p class="short-description"><?php echo $helperao->getHtmlSubstring($_product->getShortDescription(), 90); ?></p>
        <div href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn primary-button"><p><?php echo $this->__('Learn More') ?></p></div>
    <?php if($_btn_buy) :?>
        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart sel-add-to-cart primary-button" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product);  ?>;event.stopPropagation();')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
    <?php endif;?>
    </a>
</div>