<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
	<div class="product-grid-mea">
	<ul class="products-grid">
		<?php $_columnCount = $this->getColumnCount(); ?>
    	<?php foreach ($_products->getItems() as $_product) : ?>
		<li class="item">
			<?php
				$this->getChild("mini-fiche")->setData("product", $_product);
				echo $this->getChildHtml("mini-fiche", false);
			?>
		</li>
	    <?php endforeach; ?>
	</ul>
	</div>
<?php endif;  ?>