<div class="footer-container">
    <div class="footer">
        <span><b>Livraison offerts</b> en boutique</span>
        <span><b>Satisfait</b> ou remboursé</span>
        <span><b>Paiement</b> 100 % sécurisé</span>
        <span><b>Retour gratuit</b> sous 15 jours</span>
        <span><b>Aide et conseils</b> <?php echo Mage::getStoreConfig('general/store_information/phone') ?></span>
    </div>
</div>