<?php
	$solrData = $this->getSolrData();
	$stats = $solrData['stats'];
	$facets = $solrData['facet_counts'];
	$facets_fields = $facets['facet_fields'];
	$facets_fields_labels = Mage::getSingleton('core/session')->getSolrFacetFieldsLabels();

	$q = $this->getData('querytext');
	
	$solrModel = Mage::getModel('solrsearch/solr');
	$filterQuery =$solrModel->getStandardFilterQuery();
	$isFacetActived = false;
	foreach($filterQuery as $key=>$value) {
		if(is_array($value) && count($value) > 0) {
		$isFacetActived = true;
		}
	}
?>
<div class="block block-layered-nav" id="solr_search_facets">
    <div class="block-title">
        <strong><span><?php echo $this->helper('catalog')->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content">
    	<form name="searchFacets" method="get" action="<?php echo $this->helper('solrsearch')->getResultUrl() ?>">
			<input type="hidden" name="q" value="<?php echo $q ?>" />
    		<?php if($isFacetActived) : ?>
			<div class="currently">
				<p class="block-subtitle block-subtitle-solr"><span class="blue"><?php echo $this->helper('catalog')->__('Filtres') ?></span> <?php echo $this->helper('catalog')->__('ACTIFS') ?></p>
				<ol <?php if (count($filterQuery) > 10) : ?> class="solr_scroll_list" <?php endif; ?>>
					<?php foreach($filterQuery as $key=>$values): ?>
						<?php foreach($values as $v): ?>
							<li>
								<span class="label"><?php echo $this->getFacetLabel($key); ?>:</span> <span class="value"><?php echo $v ?></span>
								<?php $face_key = substr($key, 0, strrpos($key, '_'))?>
								<a title="<?php echo $this->helper('catalog')->__('Remove This Item') ?>" href="<?php echo $this->getRemoveFacesUrl($face_key, $v)?>" class="btn-remove"><?php echo $this->helper('catalog')->__('Remove This Item') ?></a>
								<?php if ($face_key != 'price'):?>
								<input type="hidden" name="fq[<?php echo $face_key ?>]" value="<?php echo $v?>" />
								<?php endif;?>
							</li>
						<?php endforeach; ?>
					<?php endforeach; ?>
				</ol>
			</div>
			<?php endif; ?>
            <p class="block-subtitle block-subtitle-solr"><span class="blue"><?php echo $this->helper('catalog')->__('FILTRER') ?></span> <?php echo $this->helper('catalog')->__('PAR') ?></p>
            <dl id="narrow-by-list">
				<?php foreach ($facets_fields as $key=>$face): ?>
                    <?php if (count($face) > 0):?>
                    <dt id="solr_search_<?php echo $key ?>_expander" onclick="Effect.toggle('content_holder_<?php echo $key ?>', 'slide', { duration: 0.3 }); $('solr_search_<?php echo $key ?>_expander').toggleClassName('collapsed'); return false;"><?php echo $this->getFacetLabel($key); ?></dt>
                    <dd id="content_holder_<?php echo $key ?>">
                    	<?php if ($key == 'category_path'):?>
                    		<?php $this->parseCategoryPathFacet($face); ?>
                    	<?php else:?>
                    	<ol>
                    		<?php foreach ($face as $item=>$count): ?>
                    		<?php if ($count > 0):?>
			                   	<li>							
								<?php $face_key = substr($key, 0, strrpos($key, '_'))?>
								<?php 
										$activeClass = '';
										$facetUrl = $this->getFacesUrl(array('fq'=>array($face_key=>$item)));
										if (isset($filterQuery[$key]) && in_array($item, $filterQuery[$key])){
											$activeClass = 'active';
											$facetUrl = $this->getRemoveFacesUrl($face_key, $v);
										}?>
										<a href="<?php echo $facetUrl?>" class="facet-item <?php echo $activeClass;?>"><?php echo $item?></a> (<?php echo $count?>)
								</li>
							<?php endif;?>
		                	<?php endforeach; ?>
                    	</ol>
                  		<?php endif; ?>
                    </dd>
                    <?php endif;?>
                <?php endforeach; ?>
                
                <?php if (floor($stats['stats_fields']['price_decimal']['max']) > 0 && floor($stats['stats_fields']['price_decimal']['max']) != floor($stats['stats_fields']['price_decimal']['min'])) :?>
                <dt id="solr_search_prize_expander" onclick="Effect.toggle('content_holder_prize', 'slide', { duration: 0.3 }); $('solr_search_prize_expander').toggleClassName('collapsed'); return false;"><?php echo $this->helper('catalog')->__('Prices') ?></dt>
				<dd id="content_holder_prize">
					<div id="refine-results-price">
					    <div class="ui-textured-darkgrey-block">
					        <div class="refine-results-price-slider" id="solr_search_price_slider">
					            <div id="refine-results-price-range" class="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all">
					            	<div class="ui-slider-range ui-widget-header"></div>
					            		<span id="solr_search_price_slider_handle1" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 0%;"></span>
					            		<span id="solr_search_price_slider_handle2" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 100%;"></span>
					            	</div>
					        </div>
					        <div id="refine-results-price-values">
					            <?php $currencySign = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() ?>
					            <input type="text" id="solr_search_price_slider_start_value" value="<?php echo floor($stats['stats_fields']['price_decimal']['min']) ?>"/><?php echo $currencySign?> - <input type="text" id="solr_search_price_slider_end_value" value="<?php echo ceil($stats['stats_fields']['price_decimal']['max']) ?>" />
					            <?php echo $currencySign?>
					            
					        	<?php 
					        	$minPrice = floor($stats['stats_fields']['price_decimal']['min']);
					        	$maxPrice = ceil($stats['stats_fields']['price_decimal']['max']);
					        	
					        	if (isset($filterQuery['price']) && !empty($filterQuery['price'][0])) {
					        		
					        		$priceArray = explode(' TO ', $filterQuery['price'][0]);
					        		if (isset($priceArray[0]) && $priceArray[0] > 0){
										$minPrice = $priceArray[0];
					        		}else{
					        			$minPrice = 0;
					        		}
					        		
					        		if (isset($priceArray[1]) && $priceArray[1] > 0){
										$maxPrice = $priceArray[1];
					        		}else{
					        			$maxPrice = 0;
					        		}
					        		
					        	}
					        	?>
					        	
					        	<input type="hidden" name="fq[price]" id="price_hidden_value" value="<?php echo floor($minPrice) ?> TO <?php echo ceil($maxPrice) ?>" />
					            </div>
					        <button title="<?php echo $this->helper('catalog')->__('Update Price Range') ?>" onclick="set_hidden_price_value();" id="refine-results-price-apply" class="ui-button ui-button-grey" type="submit"><?php echo $this->helper('catalog')->__('Update Price Range') ?></button>
					    </div>
					</div>
					<script type="text/javascript">						
						// <![CDATA[
							var handles = ['solr_search_price_slider_handle1', 'solr_search_price_slider_handle2'];
							// horizontal slider control
							new Control.Slider(handles, 'solr_search_price_slider', {
								range:$R(<?php echo floor($stats['stats_fields']['price_decimal']['min']) ?>, <?php echo ceil($stats['stats_fields']['price_decimal']['max']) ?>),
								step:10,
								restricted:true,
								sliderValue:[<?php echo floor($stats['stats_fields']['price_decimal']['min']) ?>,<?php echo ceil($stats['stats_fields']['price_decimal']['max']) ?>],
								onSlide: function(v) { 
									$('solr_search_price_slider_start_value').value = Math.round(v[0]);
									$('solr_search_price_slider_end_value').value = Math.round(v[1]);
								},
								onChange: function(v) {
									$('solr_search_price_slider_start_value').value = Math.round(v[0]);
									$('solr_search_price_slider_end_value').value = Math.round(v[1]);
								}
							});
							function set_hidden_price_value() {
								var startValue = $('solr_search_price_slider_start_value').value;
								var endValue = $('solr_search_price_slider_end_value').value;
								$('price_hidden_value').value = startValue+' TO '+endValue;
							}	
						// ]]>
					</script>
				</dd>
				<?php endif;?>
            </dl>
            </form>           
    </div>
</div>