<?php 
	$q = "";
	if($this->getRequest()->getParams('q') != ""){
		$params = $this->getRequest()->getParams();
		if(isset($params['q'])){
			$q = $params['q'];
		}
	}

	
	$display_thumb = Mage::getStoreConfig('webmods_solrsearch/settings/solr_quick_search_display_thumnail', $this->getStoreId());
	
	$allow_filter = Mage::getStoreConfig('webmods_solrsearch/settings/solr_quick_search_allow_filter', $this->getStoreId());
	
	$solr_index = Mage::getStoreConfig('webmods_solrsearch/settings/solr_index', $this->getStoreId());
	
	$queryFields = "";
	$solrsearchconfig = Mage::getStoreConfig('webmods_solrsearch_fields/settings/enabled_fields', $this->getStoreId());
	
	$fieldConfigArray = explode(",",$solrsearchconfig);
	
	$entityType = Mage::getModel('eav/config')->getEntityType('catalog_product');
	$catalogProductEntityTypeId = $entityType->getEntityTypeId();
	
	
	$attributesInfo = Mage::getResourceModel('eav/entity_attribute_collection')
	->setEntityTypeFilter($catalogProductEntityTypeId)
	->setCodeFilter($fieldConfigArray)
	->addSetInfo()
	->getData();
			
	foreach($attributesInfo as $att){
		$queryFields .= $att['attribute_code']."_".$att['backend_type'];
		if(isset($att['solr_search_field_weight']) && !empty($att['solr_search_field_weight']) && $att['solr_search_field_weight'] > 0){
			$queryFields .= "^".$att['solr_search_field_weight'];
		}	
		$queryFields .= " ";	
	}	
?>
<form id="search_mini_form" action="<?php echo $this->helper('solrsearch')->getResultUrl() ?>" method="get">
    <div class="form-search">
        <label for="search"><?php echo $this->helper('catalog')->__('Search:') ?></label>
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo trim(trim($this->helper('catalogsearch')->getEscapedQueryText(),'"')) ?>" class="input-text" />
        <button type="submit" title="<?php echo $this->helper('catalog')->__('Search') ?>" class="button"><span><span><?php echo $this->helper('catalogsearch')->__('Search') ?></span></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
        //<![CDATA[
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
            //searchForm.initAutocomplete('<?php echo $this->helper('catalogsearch')->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
        </script>
        <script type="text/javascript">
        //<![CDATA[           

            var Manager;
			/**
			 * Initiate a main point to contact with Solr
			 */
			Manager = new AjaxSolr.Manager({
		      solrUrl: '<?php echo $this->getUrl('/') ?>search/ajax/query?r='
		    });
		    
            Manager.addWidget(new AjaxSolr.AutocompleteWidget({
			  id: 'autocomplete',
			  target: '#search_mini_form',
			  currencySign: '<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() ?>',
			  field: 'autosuggest',
			  ajaxBaseUrl: '<?php echo $this->getUrl('/');?>',
			  mediaUrl: '<?php echo  Mage::getStoreConfig('web/unsecure/base_media_url');?>',
			  queryFields: '<?php echo trim(str_replace("_int","_text",$queryFields)," ")?>',
			  displayThumb: '<?php echo $display_thumb ;?>',
			  allowFilter: '<?php echo $allow_filter?>'
			}));			
			Manager.init();
        //]]>
        </script>
    </div>
</form>