<?php

	$solrData = $this->getSolrData();
	$stats = $solrData['stats'];
	$facets = $solrData['facet_counts'];
	$facets_fields = $facets['facet_fields'];
	$facets_fields_labels = Mage::getSingleton('core/session')->getSolrFacetFieldsLabels();
	
	$q = $this->getData('querytext');
	
	$solrModel = Mage::getModel('solrsearch/solr');
	$filterQuery =$solrModel->getStandardFilterQuery();
	$isFacetActived = false;
	foreach($filterQuery as $key=>$value) {
		if(is_array($value) && count($value) > 0) {
			$isFacetActived = true;
		}
	}
?>
<div class="block block-layered-nav" id="solr_search_facets">
    <div class="block-title">
        <strong><span><?php echo $this->helper('catalog')->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content">
            <?php if($isFacetActived) : ?>
			<div class="currently">
				<p class="block-subtitle"><?php echo $this->helper('catalog')->__('Currently Shopping by:') ?></p>
				<ol>
					<?php foreach($filterQuery as $key=>$values): ?>
						<?php foreach($values as $v): ?>
							<li>
								<span class="label"><?php echo $this->getFacetLabel($key); ?>:</span> <span class="value"><?php echo $v ?></span>
								<a title="<?php echo $this->helper('catalog')->__('Remove This Item') ?>" href="javascript:;" onclick="solrsearch_resultpage_ajax_request(this, '<?php echo $key ?>|<?php echo $v ?>');" class="btn-remove"><?php echo $this->helper('catalog')->__('Remove This Item') ?></a>
							</li>
						<?php endforeach; ?>
					<?php endforeach; ?>
				</ol>
			</div>
			<?php endif; ?>
            <p class="block-subtitle"><?php echo $this->helper('catalog')->__('Shopping Options') ?></p>
            <dl id="narrow-by-list">
				<?php foreach ($facets_fields as $key=>$face): ?>
                    <?php if (count($face) > 0):?>
                    <dt class="solr_search_title <?php if (count($face) > 10) : ?> solr_scroll_list_not_expendable <?php endif; ?>" id="solr_search_<?php echo $key ?>_expander" onclick="Effect.toggle('content_holder_<?php echo $key ?>', 'slide', { duration: 0.3 }); $('solr_search_<?php echo $key ?>_expander').toggleClassName('collapsed'); return false;"><?php echo $this->getFacetLabel($key); ?></dt>
                    <dd id="content_holder_<?php echo $key ?>">
                    	<ol <?php if (count($face) > 10) : ?> class="solr_scroll_list" <?php endif; ?>>
                    		<?php foreach ($face as $item=>$count): ?>
                    		<?php if ($count > 0): ?>
			                   	<li>							
								<a href="javascript:;" onclick="solrsearch_resultpage_ajax_request(this, '<?php echo $key.'|'.$item ?>');" class="facet-item"><?php echo $item?></a> (<?php echo $count?>)
								</li>
							<?php endif;?>
		                	<?php endforeach; ?>
                    	</ol>
                    </dd>
                    <?php endif;?>
                <?php endforeach; ?>
                
				<dt id="solr_search_prize_expander" onclick="Effect.toggle('content_holder_prize', 'slide', { duration: 0.3 }); $('solr_search_prize_expander').toggleClassName('collapsed'); return false;">Prix</dt>
				<dd id="content_holder_prize">
					<div id="refine-results-price">
					    <div class="ui-textured-darkgrey-block">
					    	<div class="slider-border"></div>
					        <div class="refine-results-price-slider" id="solr_search_price_slider">
					            <div id="refine-results-price-range" class="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all">
					            	<div class="ui-slider-range ui-widget-header"></div>
					            		<span id="solr_search_price_slider_handle1" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 0%;"></span>
					            		<span id="solr_search_price_slider_handle2" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 100%;"></span>
					            	</div>
					        </div>
					        <div id="refine-results-price-values">
					            <?php $currencySign = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() ?>
					            
					            <input type="text" id="solr_search_price_slider_start_value" value="<?php echo floor($stats['stats_fields']['price_decimal']['min']) ?>"/><?php echo $currencySign?> Jusqu'&agrave; <input type="text" id="solr_search_price_slider_end_value" value="<?php echo ceil($stats['stats_fields']['price_decimal']['max']) ?>" /><?php echo $currencySign?>
					        	
					        </div>
					        <button title="<?php echo $this->helper('catalog')->__('Update Price Range') ?>" onclick="solrsearch_resultpage_ajax_request(this, 'price_decimal|'+'['+$('solr_search_price_slider_start_value').value+' TO '+$('solr_search_price_slider_end_value').value+']')" id="refine-results-price-apply" class="ui-button ui-button-grey" type="button"><?php echo $this->helper('catalog')->__('Update Price Range') ?></button>
					    </div>
					</div>
					<script type="text/javascript">						
						// <![CDATA[
							var handles = ['solr_search_price_slider_handle1', 'solr_search_price_slider_handle2'];
							// horizontal slider control
							new Control.Slider(handles, 'solr_search_price_slider', {
								range:$R(<?php echo floor($stats['stats_fields']['price_decimal']['min']) ?>, <?php echo ceil($stats['stats_fields']['price_decimal']['max']) ?>),
								step:10,
								restricted:true,
								sliderValue:[<?php echo floor($stats['stats_fields']['price_decimal']['min']) ?>,<?php echo ceil($stats['stats_fields']['price_decimal']['max']) ?>],
								onSlide: function(v) { 
									$('solr_search_price_slider_start_value').value = Math.round(v[0]);
									$('solr_search_price_slider_end_value').value = Math.round(v[1]);
								},
								onChange: function(v) {
									$('solr_search_price_slider_start_value').value = Math.round(v[0]);
									$('solr_search_price_slider_end_value').value = Math.round(v[1]);
								}
							});
	
						// ]]>
					</script>
				</dd>
            </dl>           
    </div>
</div>
<script type="text/javascript">
 

	function solrsearch_resultpage_ajax_request(obj, filter){		
		if($(obj).hasClassName('active')) {
			$(obj).removeClassName('active');
			filter = filter+'|0';
		}else if($(obj).hasClassName('btn-remove')){
			filter = filter+'|0';
		}else{
			$(obj).addClassName('active');
			filter = filter+'|1';
		}
		
		
		//var priceRange = '['+$('solr_search_price_slider_start_value').value+' TO '+$('solr_search_price_slider_end_value').value+']';
		//filter += ',price_decimal|'+priceRange+'|';
		
		new Ajax.Request(
			'<?php echo $this->getUrl('/'); ?>search/ajax/ajaxresult',{
				parameters:{ q:'<?php echo $q ?>',filterQuery:filter},
				onCreate: function(response) {
					//do something
					Dialog.info('<img src="<?php echo trim(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN),'/').'/frontend/base/default/solrsearch/images/ajax-loader.gif'; ?>" />',{className:"solrsearch", width: 50, height: 100})
				},
				onSuccess: function(response) {
					//Do something
				},
				onFailure: function(response) {
					//do some thing
				},
				onComplete: function(response) {
					
					$('solr_search_result_page_container').update(response.responseText);
					$('solr_search_facets').update($('solr_search_facets_temp').innerHTML);
					if(document.getElementById('solr_search_facets_temp')){
						$('solr_search_facets_temp').remove();
					}
					Dialog.closeInfo();
				}
			}
		);
	}
	
	function solrsearch_resultpage_ajax_refine(){
		new Ajax.Request(
			'<?php echo $this->getUrl('/'); ?>search/ajax/ajaxresult',{
				parameters:{ q:'<?php echo $q ?>',refineSearch:'yes'},
				onCreate: function(response) {
					//do something
					Dialog.info('<img src="<?php echo trim(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN),'/').'/frontend/base/default/solrsearch/images/ajax-loader.gif'; ?>" />',{className:"solrsearch", width: 50, height: 100})
				},
				onSuccess: function(response) {
					//Do something
				},
				onFailure: function(response) {
					//do some thing
				},
				onComplete: function(response) {
					
					$('solr_search_result_page_container').update(response.responseText);
					$('solr_search_facets').update($('solr_search_facets_temp').innerHTML);
					if(document.getElementById('solr_search_facets_temp')){
						$('solr_search_facets_temp').remove();
					}
					Dialog.closeInfo();
				}
			}
		);
	}
</script>